### ISSUE TITLE
Var arg functions fail

### ISSUE THREAD

**Issue by LeifAndersen** [LeifAndersen/interactive-syntax-clojure#7]
The following clojurescript 'should' be valid, but fails:

```
(defn munge-res [a & b]
  (println a)
  (println b)
  42)

(println (munge-res 1 2))
```

Gives this output:

```
Error: .slice requires 2 arguments
	* Line 318: in (anonymous function)
	* Line 17: in cljs$user$munge_res
	* Line 39: in (anonymous function)
Runtime Stack:
Error: .slice requires 2 arguments
    at Array.funExpr9 [as slice] (webpack://interactive-syntax/./node_modules/@stopify/higher-order-functions/dist/ts/simpleHofPolyfill.lazy.js?:1713:15)
    at cljs$user$munge_res (eval at evalCompiled (webpack://interactive-syntax/./node_modules/@leifandersen/stopify-tweak/dist/src/entrypoints/compiler.js?), <anonymous>:1:3347)
    at funExpr0 (eval at evalCompiled (webpack://interactive-syntax/./node_modules/@leifandersen/stopify-tweak/dist/src/entrypoints/compiler.js?), <anonymous>:1:7761)
    at LazyRuntime.abstractRun (webpack://interactive-syntax/./node_modules/@stopify/continuations-runtime/dist/src/runtime/lazyRuntime.js?:42:23)
    at LazyRuntime.runtime (webpack://interactive-syntax/./node_modules/@stopify/continuations-runtime/dist/src/runtime/abstractRuntime.js?:69:33)
    at Runner.evalCompiled (webpack://interactive-syntax/./node_modules/@leifandersen/stopify-tweak/dist/src/entrypoints/compiler.js?:60:31)
    at run (http://localhost:9501/cljs-out/dev/interactive_syntax/env.js:492:17)
    at Worker.<anonymous> (http://localhost:9501/cljs-out/dev/interactive_syntax/env.js:556:12)
```

The compiled javascript is:

```
VM8948 react_devtools_backend.js:4045 cljs.user.munge_res = (function cljs$user$munge_res(var_args){
var args__41777__auto__ = [];
var len__41774__auto___927 = arguments.length;
var i__41775__auto___928 = (0);
while(true){
if((i__41775__auto___928 < len__41774__auto___927)){
args__41777__auto__.push((arguments[i__41775__auto___928]));

var G__929 = (i__41775__auto___928 + (1));
i__41775__auto___928 = G__929;
continue;
} else {
}
break;
}

var argseq__41778__auto__ = ((((1) < args__41777__auto__.length))?(new cljs.core.IndexedSeq(args__41777__auto__.slice((1)),(0),null)):null);
return cljs.user.munge_res.cljs$core$IFn$_invoke$arity$variadic((arguments[(0)]),argseq__41778__auto__);
});

(cljs.user.munge_res.cljs$core$IFn$_invoke$arity$variadic = (function (a,b){
visr.core.println.call(null,a);

visr.core.println.call(null,b);

return (42);
}));

(cljs.user.munge_res.cljs$lang$maxFixedArity = (1));

/** @this {Function} */
(cljs.user.munge_res.cljs$lang$applyTo = (function (seq925){
var G__926 = cljs.core.first.call(null,seq925);
var seq925__$1 = cljs.core.next.call(null,seq925);
var self__41765__auto__ = this;
return self__41765__auto__.cljs$core$IFn$_invoke$arity$variadic(G__926,seq925__$1);
}));

visr.core.println.call(null,cljs.user.munge_res.call(null,(1),(2)));
```

**Comment by LeifAndersen** [comment]
5a1252454d210f445afed2a97436168df501009b fixes this.
